name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-15  # 或者 macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          brew install --cask docker  # 使用 Homebrew 安装 Docker
          open /Applications/Docker.app  # 启动 Docker
          sleep 30  # 等待 Docker 启动完成

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t nano:latest .

      - name: Push Docker Image
        run: |
          docker push nano:latest
